version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env.db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: gunicorn admin.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web
  tgbot:
      container_name: bot
      build:
        context: .
      command: python app.py
      volumes:
        - .:/src
      restart: always
      env_file:
        - .env
      depends_on:
        - db
        - web
        - redis

volumes:
  static_volume:
  media_volume:
  postgres_data: